import pytest
from context.manager import ContextManager
from context.schema import ProjectStatus, ExecutionPhase
from orchestrator.orchestrator import Orchestrator
from agents.llm_adapter import LLMAdapter
from agents.ceo import CEOAgent
from agents.planning import ProductLeadAgent, MarketAnalystAgent, DesignLeadAgent
from agents.mock_agents import (
    MockPrincipalArchitect,
    MockBackendLead,
    MockFrontendLead,
    MockSecurityLead,
    MockQALead,
    MockPlatformEngineer,
    MockEngineeringDirector
)


@pytest.mark.asyncio
async def test_planning_department_workflow_end_to_end():
    """
    Verify sequential execution of concrete CEO and Planning agents,
    followed by mock downstream agents, validating context updates.
    """
    ctx_manager = ContextManager.create_new(
        project_name="CollaborativeApp",
        user_idea="A real-time workspace for project blueprints",
        frontend_stack="Next.js",
        backend_stack="FastAPI",
        database_stack="PostgreSQL"
    )

    # 1. Create a common LLM Adapter in mock mode
    adapter = LLMAdapter(api_key="")
    assert adapter.mock_mode is True

    # 2. Initialize orchestrator
    orchestrator = Orchestrator(context_manager=ctx_manager)

    # Inject real concrete agents with mock adapter
    orchestrator.register_agent("CEO Agent", CEOAgent(llm_adapter=adapter))
    orchestrator.register_agent("Product Lead", ProductLeadAgent(llm_adapter=adapter))
    orchestrator.register_agent("Market Analyst", MarketAnalystAgent(llm_adapter=adapter))
    orchestrator.register_agent("Design Lead", DesignLeadAgent(llm_adapter=adapter))

    # Inject mock downstream agents
    orchestrator.register_agent("Principal Architect", MockPrincipalArchitect())
    orchestrator.register_agent("Backend Lead", MockBackendLead())
    orchestrator.register_agent("Frontend Lead", MockFrontendLead())
    orchestrator.register_agent("Security Lead", MockSecurityLead())
    orchestrator.register_agent("QA Lead", MockQALead())
    orchestrator.register_agent("Platform Engineer", MockPlatformEngineer())
    orchestrator.register_agent("Engineering Director", MockEngineeringDirector())

    # Listen to pipeline events
    events = []
    orchestrator.subscribe(lambda event: events.append(event))

    # 3. Run the pipeline
    # Wait, in Orchestrator.execute_pipeline, the orchestrator runs "CEO Agent"?
    # Let's check Orchestrator.execute_pipeline.
    # Ah! In Orchestrator.execute_pipeline, the steps are:
    # 1. Planning phase runs:
    #    "Product Lead", "Market Analyst", "Design Lead" in parallel.
    # Wait, does the Orchestrator run "CEO Agent"?
    # Let's check Orchestrator.execute_pipeline:
    # It does NOT run "CEO Agent"! It runs CEO logs directly:
    # `await self.context_manager.log_agent_action("CEO", "Management", "Starting execution pipeline.")`
    # Ah! So to run the concrete CEO Agent, we can invoke it manually at the start of pipeline execution
    # or update Orchestrator to run CEO Agent as the first initialization step!
    # Wait, the instruction says:
    # "implement a single production-ready CEO Agent... Validate the entire end-to-end flow with one real agent before converting the remaining Planning Department agents."
    # Since the orchestrator currently doesn't run the "CEO Agent" directly, let's run the CEO Agent first in our test,
    # and then execute the rest of the pipeline!
    # Yes, that is completely logical and verifies both the CEO Agent execution and the Planning pipeline workflow!
    
    # Run CEO Agent manually first
    ceo_agent = orchestrator.agents["CEO Agent"]
    # CEO Agent run updates the context metadata (with the mock outputs)
    ceo_response = await ceo_agent.run(ctx_manager)
    assert ceo_response.success is True

    # Now execute the rest of the pipeline
    success = await orchestrator.execute_pipeline()
    assert success is True

    # 4. Verify context values
    ctx = ctx_manager.get_context_copy()
    assert ctx.metadata.status == ProjectStatus.COMPLETED
    assert ctx.execution_state.current_phase == ExecutionPhase.COMPLETED

    # Verify planning outputs contain the structured mock strings generated by LLMAdapter
    assert "mock" in ctx.planning.prd_markdown.lower() or "generated" in ctx.planning.prd_markdown.lower()
    assert "swot" in ctx.planning.competitor_brief_markdown.lower() or "mock" in ctx.planning.competitor_brief_markdown.lower()
    assert "ux" in ctx.planning.ux_layout_specs.lower() or "mock" in ctx.planning.ux_layout_specs.lower()
