"""
Agent response and state data models.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class AgentStatus(str, Enum):
    IDLE = "IDLE"
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"


class AgentResponse(BaseModel):
    """
    Standard response object returned by all agent executions.
    """
    agent_name: str = Field(..., description="Name of the executing agent")
    success: bool = Field(..., description="Flag indicating if the agent completed successfully")
    output_data: Dict[str, Any] = Field(default_factory=dict, description="Structured output payload generated by the agent")
    error_message: Optional[str] = Field(None, description="Detailed error description if execution failed")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Metadata metrics like tokens, duration, etc.")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Time when the execution finished")
