"""
Shared Project Context Schema definitions using Pydantic v2.

This schema maps 1:1 with the JSON Schema defined in the System Architecture Document.
It serves as the single source of truth for the project state during the autonomous run.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────────────

class ProjectStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ExecutionPhase(str, Enum):
    PLANNING = "PLANNING"
    ARCHITECTURE = "ARCHITECTURE"
    ENGINEERING = "ENGINEERING"
    VALIDATION = "VALIDATION"
    REVIEW = "REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# ── Nested Models ─────────────────────────────────────────────────────────────

class TechStack(BaseModel):
    frontend: str = Field(..., description="Frontend framework and libraries (e.g. Next.js + Tailwind)")
    backend: str = Field(..., description="Backend framework (e.g. FastAPI)")
    database: str = Field(..., description="Database engine (e.g. PostgreSQL)")


class ProjectMetadata(BaseModel):
    project_id: UUID = Field(default_factory=uuid4, description="Unique UUID for this generation workspace")
    project_name: str = Field(..., description="Name of the software project being forged")
    user_idea: str = Field(..., description="The user's raw idea text input")
    tech_stack: TechStack = Field(..., description="Selected technology stack parameters")
    version: str = Field(default="1.0.0", description="Blueprint specification version")
    status: ProjectStatus = Field(default=ProjectStatus.PENDING, description="Current workflow state")


class PlanningContext(BaseModel):
    prd_markdown: str = Field(default="", description="Detailed Product Requirements Document generated by Product Lead")
    competitor_brief_markdown: str = Field(default="", description="SWOT and competitor analysis generated by Market Analyst")
    ux_layout_specs: str = Field(default="", description="Visual navigation layouts mapped by Design Lead")


class ArchitectureContext(BaseModel):
    topology_markdown: str = Field(default="", description="System architecture and C4 diagrams generated by Principal Architect")
    design_rationale: str = Field(default="", description="Technical explanations for structural choices")


class EngineeringContext(BaseModel):
    api_spec_yaml: str = Field(default="", description="OpenAPI 3.0 configuration schema generated by Backend Lead")
    database_schema_sql: str = Field(default="", description="SQL database schema schema DDL generated by Backend Lead")
    backend_main_py: str = Field(default="", description="FastAPI main application skeleton generated by Backend Lead")

    # Backend Lead new fields
    backend_architecture: str = Field(default="", description="High-level backend architecture overview.")
    backend_services: List[str] = Field(default_factory=list, description="List of backend services and their responsibilities.")
    api_design: str = Field(default="", description="API endpoint recommendations and controller layout.")
    database_notes: str = Field(default="", description="Database design notes, indexing, and improvements.")
    folder_structure_backend: str = Field(default="", description="Folder layout structure of the backend application.")
    security_notes: str = Field(default="", description="Authentication strategy and security recommendations.")

    # Frontend Lead new fields
    frontend_architecture: str = Field(default="", description="High-level frontend architecture and patterns.")
    frontend_pages: List[str] = Field(default_factory=list, description="Page hierarchy list with descriptions.")
    routing: str = Field(default="", description="Frontend routing plan details.")
    components: List[str] = Field(default_factory=list, description="Reusable UI components list with responsibilities.")
    layout: str = Field(default="", description="Layout guidelines and component tree structure.")
    state_management: str = Field(default="", description="State management recommendations.")
    styling_approach: str = Field(default="", description="Styling approach and style guide guidelines.")
    accessibility_checklist: List[str] = Field(default_factory=list, description="Checklist for accessibility (WCAG).")
    responsive_design: str = Field(default="", description="Responsive layouts and design strategy.")
    folder_structure_frontend: str = Field(default="", description="Frontend folder organization diagram.")


class DevOpsConfigs(BaseModel):
    dockerfile: str = Field(default="", description="Dockerfile scaffolding")
    docker_compose_yml: str = Field(default="", description="Docker Compose configuration skeleton")


class ValidationContext(BaseModel):
    security_report_markdown: str = Field(default="", description="Threat models and vulnerability mitigations generated by Security Lead")
    test_plan_markdown: str = Field(default="", description="Unit, Integration, and E2E QA plans generated by QA Lead")
    devops_configs: DevOpsConfigs = Field(default_factory=DevOpsConfigs, description="Deployment files structured by Platform Engineer")

    # Security Lead new fields
    auth_recommendations: str = Field(default="", description="Authentication recommendations.")
    authorization_strategy: str = Field(default="", description="Authorization rules and scopes.")
    secret_management: str = Field(default="", description="Secret storage and management strategies.")
    owasp_checklist: List[str] = Field(default_factory=list, description="Strict checklist checking against OWASP Top 10.")
    api_security: str = Field(default="", description="API hardening and access policies.")
    input_validation: str = Field(default="", description="Input validation, sanitization, and typing.")
    rate_limiting: str = Field(default="", description="Rate limiting algorithms and thresholds.")
    encryption_recommendations: str = Field(default="", description="Encryption standards in transit and at rest.")
    dependency_risks: List[str] = Field(default_factory=list, description="Identified third-party dependencies security risks.")
    production_security_checklist: List[str] = Field(default_factory=list, description="Final validation checklist before production.")

    # QA Lead new fields
    unit_testing_strategy: str = Field(default="", description="Unit testing frameworks and guidelines.")
    integration_tests: str = Field(default="", description="Integration testing boundaries and setups.")
    api_tests: str = Field(default="", description="API validation and boundary testing rules.")
    frontend_testing: str = Field(default="", description="Frontend testing frameworks, E2E, and components.")
    edge_cases: List[str] = Field(default_factory=list, description="Crucial boundary conditions and edge cases.")
    acceptance_criteria: List[str] = Field(default_factory=list, description="Acceptance criteria checklist.")
    regression_testing: str = Field(default="", description="Strategy for regression detection.")
    manual_testing_checklist: List[str] = Field(default_factory=list, description="Manual testing checklist.")
    quality_risks: List[str] = Field(default_factory=list, description="Identified quality and failure risks.")

    # Platform Engineer new fields
    deployment_strategy: str = Field(default="", description="Deployment patterns.")
    ci_cd_pipeline: str = Field(default="", description="CI/CD pipeline specifications.")
    cloud_recommendations: str = Field(default="", description="Cloud providers and services.")
    observability: str = Field(default="", description="APM monitoring and tracing.")
    monitoring: str = Field(default="", description="System health metrics and alerts.")
    logging: str = Field(default="", description="Log formatting, storage, and retention.")
    scalability: str = Field(default="", description="Scaling boundaries and replica thresholds.")
    backup_strategy: str = Field(default="", description="Database backup retention schedules.")
    production_readiness: List[str] = Field(default_factory=list, description="Platforms checklist verifying readiness.")


class ReviewContext(BaseModel):
    approved: bool = Field(default=False, description="Approval gate status checked by Engineering Director")
    reviewer_feedback: List[str] = Field(default_factory=list, description="Revision feedback items listed by Engineering Director")


class TimelineLogItem(BaseModel):
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Log entry timestamp")
    agent_name: str = Field(..., description="Name of the agent logging the event")
    department: str = Field(..., description="Department the agent belongs to")
    message: str = Field(..., description="Action log message description")


class ExecutionMetrics(BaseModel):
    start_time: datetime = Field(default_factory=datetime.utcnow, description="Time project generation started")
    end_time: Optional[datetime] = Field(default=None, description="Time project generation completed")
    total_tokens_used: int = Field(default=0, description="Total running token count consumed across all agents")


class ExecutionState(BaseModel):
    current_phase: ExecutionPhase = Field(default=ExecutionPhase.PLANNING, description="Active execution phase gate")
    active_agents: List[str] = Field(default_factory=list, description="Currently running active agents list")
    timeline_logs: List[TimelineLogItem] = Field(default_factory=list, description="SSE streaming audit log list")
    metrics: ExecutionMetrics = Field(default_factory=ExecutionMetrics, description="Resource utilization metrics")


# ── Root Context Model ────────────────────────────────────────────────────────

class SharedProjectContext(BaseModel):
    metadata: ProjectMetadata = Field(..., description="Base workspace metadata details")
    planning: PlanningContext = Field(default_factory=PlanningContext, description="Functional specifications slice")
    architecture: ArchitectureContext = Field(default_factory=ArchitectureContext, description="System topology slice")
    engineering: EngineeringContext = Field(default_factory=EngineeringContext, description="Code specifications slice")
    validation: ValidationContext = Field(default_factory=ValidationContext, description="Quality and safety slice")
    review: ReviewContext = Field(default_factory=ReviewContext, description="Engineering Director sign-off slice")
    execution_state: ExecutionState = Field(default_factory=ExecutionState, description="Runtime execution tracking log state")
