"""
Shared Project Context Schema definitions using Pydantic v2.

This schema maps 1:1 with the JSON Schema defined in the System Architecture Document.
It serves as the single source of truth for the project state during the autonomous run.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────────────

class ProjectStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ExecutionPhase(str, Enum):
    PLANNING = "PLANNING"
    ARCHITECTURE = "ARCHITECTURE"
    ENGINEERING = "ENGINEERING"
    VALIDATION = "VALIDATION"
    REVIEW = "REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# ── Nested Models ─────────────────────────────────────────────────────────────

class TechStack(BaseModel):
    frontend: str = Field(..., description="Frontend framework and libraries (e.g. Next.js + Tailwind)")
    backend: str = Field(..., description="Backend framework (e.g. FastAPI)")
    database: str = Field(..., description="Database engine (e.g. PostgreSQL)")


class ProjectMetadata(BaseModel):
    project_id: UUID = Field(default_factory=uuid4, description="Unique UUID for this generation workspace")
    project_name: str = Field(..., description="Name of the software project being forged")
    user_idea: str = Field(..., description="The user's raw idea text input")
    tech_stack: TechStack = Field(..., description="Selected technology stack parameters")
    version: str = Field(default="1.0.0", description="Blueprint specification version")
    status: ProjectStatus = Field(default=ProjectStatus.PENDING, description="Current workflow state")


class PlanningContext(BaseModel):
    prd_markdown: str = Field(default="", description="Detailed Product Requirements Document generated by Product Lead")
    competitor_brief_markdown: str = Field(default="", description="SWOT and competitor analysis generated by Market Analyst")
    ux_layout_specs: str = Field(default="", description="Visual navigation layouts mapped by Design Lead")


class ArchitectureContext(BaseModel):
    topology_markdown: str = Field(default="", description="System architecture and C4 diagrams generated by Principal Architect")
    design_rationale: str = Field(default="", description="Technical explanations for structural choices")


class EngineeringContext(BaseModel):
    api_spec_yaml: str = Field(default="", description="OpenAPI 3.0 configuration schema generated by Backend Lead")
    database_schema_sql: str = Field(default="", description="SQL database schema schema DDL generated by Backend Lead")
    backend_main_py: str = Field(default="", description="FastAPI main application skeleton generated by Backend Lead")


class DevOpsConfigs(BaseModel):
    dockerfile: str = Field(default="", description="Dockerfile scaffolding")
    docker_compose_yml: str = Field(default="", description="Docker Compose configuration skeleton")


class ValidationContext(BaseModel):
    security_report_markdown: str = Field(default="", description="Threat models and vulnerability mitigations generated by Security Lead")
    test_plan_markdown: str = Field(default="", description="Unit, Integration, and E2E QA plans generated by QA Lead")
    devops_configs: DevOpsConfigs = Field(default_factory=DevOpsConfigs, description="Deployment files structured by Platform Engineer")


class ReviewContext(BaseModel):
    approved: bool = Field(default=False, description="Approval gate status checked by Engineering Director")
    reviewer_feedback: List[str] = Field(default_factory=list, description="Revision feedback items listed by Engineering Director")


class TimelineLogItem(BaseModel):
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Log entry timestamp")
    agent_name: str = Field(..., description="Name of the agent logging the event")
    department: str = Field(..., description="Department the agent belongs to")
    message: str = Field(..., description="Action log message description")


class ExecutionMetrics(BaseModel):
    start_time: datetime = Field(default_factory=datetime.utcnow, description="Time project generation started")
    end_time: Optional[datetime] = Field(default=None, description="Time project generation completed")
    total_tokens_used: int = Field(default=0, description="Total running token count consumed across all agents")


class ExecutionState(BaseModel):
    current_phase: ExecutionPhase = Field(default=ExecutionPhase.PLANNING, description="Active execution phase gate")
    active_agents: List[str] = Field(default_factory=list, description="Currently running active agents list")
    timeline_logs: List[TimelineLogItem] = Field(default_factory=list, description="SSE streaming audit log list")
    metrics: ExecutionMetrics = Field(default_factory=ExecutionMetrics, description="Resource utilization metrics")


# ── Root Context Model ────────────────────────────────────────────────────────

class SharedProjectContext(BaseModel):
    metadata: ProjectMetadata = Field(..., description="Base workspace metadata details")
    planning: PlanningContext = Field(default_factory=PlanningContext, description="Functional specifications slice")
    architecture: ArchitectureContext = Field(default_factory=ArchitectureContext, description="System topology slice")
    engineering: EngineeringContext = Field(default_factory=EngineeringContext, description="Code specifications slice")
    validation: ValidationContext = Field(default_factory=ValidationContext, description="Quality and safety slice")
    review: ReviewContext = Field(default_factory=ReviewContext, description="Engineering Director sign-off slice")
    execution_state: ExecutionState = Field(default_factory=ExecutionState, description="Runtime execution tracking log state")
