"""
Artifact Generation Pipeline.

Reads details from the finalized SharedProjectContext and writes physical project files
and engineering blueprints to the target workspace directory on the disk.
"""

import os
from pathlib import Path
from typing import List
import structlog

from context.schema import SharedProjectContext
from mcp.filesystem import FilesystemMCPClient

logger = structlog.get_logger(__name__)


class ArtifactGenerator:
    """
    Scaffolds physical files from validated project context fields.
    """

    def __init__(self, context: SharedProjectContext, output_dir: Path):
        self.context = context
        self.output_dir = output_dir.resolve()

    async def generate_package(self) -> List[Path]:
        """
        Processes and writes all project blueprint artifacts to disk via FilesystemMCPClient.
        Returns a list of created file paths.
        """
        logger.info("artifact_generator_start", output_dir=str(self.output_dir))

        # Instantiate FilesystemMCPClient targeting the output directory as workspace root
        mcp_client = FilesystemMCPClient(workspace_root=self.output_dir, read_only=False)
        await mcp_client.connect()

        generated_paths = []

        try:
            # ── 1. PRD.md ────────────────────────────────────────────────────────
            prd_content = self.context.planning.prd_markdown
            if not prd_content:
                prd_content = (
                    f"# Product Requirements Document (PRD) - {self.context.metadata.project_name}\n\n"
                    f"Project Vision: {self.context.metadata.project_vision}\n"
                )
            await mcp_client.write_file("PRD.md", prd_content)
            logger.debug("artifact_file_written", path=str(self.output_dir / "PRD.md"))
            generated_paths.append(self.output_dir / "PRD.md")

            # ── 2. architecture.md ───────────────────────────────────────────────
            arch_content = (
                f"# Architecture Document - {self.context.metadata.project_name}\n\n"
                f"## System Topology Diagram\n"
                f"{self.context.architecture.topology_markdown}\n\n"
                f"## Design Rationale\n"
                f"{self.context.architecture.design_rationale}\n"
            )
            await mcp_client.write_file("architecture.md", arch_content)
            logger.debug("artifact_file_written", path=str(self.output_dir / "architecture.md"))
            generated_paths.append(self.output_dir / "architecture.md")

            # ── 3. api_spec.yaml ─────────────────────────────────────────────────
            api_content = self.context.engineering.api_spec_yaml
            if api_content:
                await mcp_client.write_file("api_spec.yaml", api_content)
                logger.debug("artifact_file_written", path=str(self.output_dir / "api_spec.yaml"))
                generated_paths.append(self.output_dir / "api_spec.yaml")

            # ── 4. database_schema.sql ───────────────────────────────────────────
            db_content = self.context.engineering.database_schema_sql
            if db_content:
                await mcp_client.write_file("database_schema.sql", db_content)
                logger.debug("artifact_file_written", path=str(self.output_dir / "database_schema.sql"))
                generated_paths.append(self.output_dir / "database_schema.sql")

            # ── 5. README.md ─────────────────────────────────────────────────────
            readme_content = self._build_readme_content()
            await mcp_client.write_file("README.md", readme_content)
            logger.debug("artifact_file_written", path=str(self.output_dir / "README.md"))
            generated_paths.append(self.output_dir / "README.md")

        finally:
            await mcp_client.disconnect()

        logger.info("artifact_generator_completed", files_written=len(generated_paths))
        return generated_paths

    def _build_readme_content(self) -> str:
        """Helper to dynamically format the project README."""
        meta = self.context.metadata
        tech = meta.tech_stack
        
        return (
            f"# ⚡ {meta.project_name}\n\n"
            f"## Product Vision\n"
            f"{meta.user_idea}\n\n"
            f"## Technology Stack Details\n"
            f"- **Frontend Framework:** {tech.frontend}\n"
            f"- **Backend Framework:** {tech.backend}\n"
            f"- **Database Engine:** {tech.database}\n\n"
            f"## Blueprint Package Files\n"
            f"- `PRD.md`: Full functional and product requirement details.\n"
            f"- `architecture.md`: Visual Mermaid topology and structural decisions.\n"
            f"- `api_spec.yaml`: OpenAPI definition scheme.\n"
            f"- `database_schema.sql`: Table structure DDL schemas.\n\n"
            f"--- \n"
            f"*Generated by DevForge AI.*"
        )
